import type {
  Skill,
  TimelineEntry,
  ResolvedTimelineEntry,
  ResourceDefinition,
  ResourceSnapshot,
} from "../types/skill";

/**
 * 指定時刻までに自動生成されたリソースの総量を計算する。
 * 戦闘開始（t=0）からカウントし、interval秒ごとに1つ生成される。
 */
function calcAutoGenerated(time: number, interval: number): number {
  if (interval <= 0) return 0;
  return Math.floor(time / interval);
}

/**
 * タイムラインエントリにリキャスト・アニメーションロックに基づく開始時刻を計算し、
 * 各エントリ時点でのリソース状態を追跡する。
 *
 * ルール:
 * - GCDスキル: 前のGCDのリキャスト完了後 かつ 前のアクションのアニメーションロック完了後
 * - oGCDスキル: 前のアクションのアニメーションロック完了後（GCDリキャスト中に使用可能）
 * - リソース: 自動生成リソースは時間経過で蓄積、スキル使用で増減
 */
export function resolveTimeline(
  entries: TimelineEntry[],
  skillMap: Map<string, Skill>,
  resources: ResourceDefinition[]
): ResolvedTimelineEntry[] {
  const resolved: ResolvedTimelineEntry[] = [];

  /** 次のGCDが使用可能になる時刻 */
  let gcdAvailableAt = 0;
  /** 次のアクション（GCD/oGCD問わず）が使用可能になる時刻 */
  let actionAvailableAt = 0;

  // リソース状態: 現在値を追跡
  const resourceState: ResourceSnapshot = {};
  // 前回の自動生成済みカウント（二重加算防止）
  const prevAutoGenCount: Record<string, number> = {};

  // リソース初期化
  for (const res of resources) {
    resourceState[res.id] = res.initialStacks ?? 0;
    prevAutoGenCount[res.id] = 0;
  }

  for (const entry of entries) {
    const skill = skillMap.get(entry.skillId);
    if (!skill) continue;

    let startTime: number;

    if (skill.type === "gcd") {
      startTime = Math.max(gcdAvailableAt, actionAvailableAt);
      gcdAvailableAt = startTime + skill.recastTime;
      actionAvailableAt = startTime + skill.animationLock;
    } else {
      startTime = actionAvailableAt;
      actionAvailableAt = startTime + skill.animationLock;
    }

    startTime = Math.round(startTime * 1000) / 1000;

    // 自動生成リソースを時刻に応じて加算
    for (const res of resources) {
      if (res.autoGenerateInterval) {
        const totalAutoGen = calcAutoGenerated(startTime, res.autoGenerateInterval);
        const newAutoGen = totalAutoGen - prevAutoGenCount[res.id];
        if (newAutoGen > 0) {
          resourceState[res.id] = Math.min(
            resourceState[res.id] + newAutoGen,
            res.maxStacks
          );
          prevAutoGenCount[res.id] = totalAutoGen;
        }
      }
    }

    // スキル実行前のリソーススナップショット
    const snapshot: ResourceSnapshot = { ...resourceState };

    // リソース不足チェック
    const resourceErrors: string[] = [];
    if (skill.resourceChanges) {
      for (const change of skill.resourceChanges) {
        if (change.amount < 0) {
          const required = Math.abs(change.amount);
          if (resourceState[change.resourceId] < required) {
            resourceErrors.push(change.resourceId);
          }
        }
      }
    }

    // リソース変動を適用（不足時でも適用し、0でクランプ）
    if (skill.resourceChanges) {
      const resourceDefMap = new Map(resources.map((r) => [r.id, r]));
      for (const change of skill.resourceChanges) {
        const def = resourceDefMap.get(change.resourceId);
        if (!def) continue;
        resourceState[change.resourceId] = Math.max(
          0,
          Math.min(
            resourceState[change.resourceId] + change.amount,
            def.maxStacks
          )
        );
      }
    }

    resolved.push({
      uid: entry.uid,
      skillId: entry.skillId,
      startTime,
      resourceSnapshot: snapshot,
      resourceErrors,
    });
  }

  return resolved;
}

/**
 * タイムライン末尾（最後のスキル実行後）のリソース状態を計算する。
 */
export function getFinalResourceState(
  resolvedEntries: ResolvedTimelineEntry[],
  skillMap: Map<string, Skill>,
  resources: ResourceDefinition[]
): ResourceSnapshot {
  if (resolvedEntries.length === 0) {
    const snapshot: ResourceSnapshot = {};
    for (const res of resources) {
      snapshot[res.id] = res.initialStacks ?? 0;
    }
    return snapshot;
  }

  // 最後のエントリのスナップショットにそのスキルの変動を適用したものが最終状態
  const last = resolvedEntries[resolvedEntries.length - 1];
  const skill = skillMap.get(last.skillId);
  const state: ResourceSnapshot = { ...last.resourceSnapshot };

  if (skill?.resourceChanges) {
    const resourceDefMap = new Map(resources.map((r) => [r.id, r]));
    for (const change of skill.resourceChanges) {
      const def = resourceDefMap.get(change.resourceId);
      if (!def) continue;
      state[change.resourceId] = Math.max(
        0,
        Math.min(state[change.resourceId] + change.amount, def.maxStacks)
      );
    }
  }

  return state;
}
