import type React from "react";
import {
  ICON_SIZE,
  LANE_HEIGHT,
  RESOURCE_LANE_HEIGHT,
  BUFF_LANE_HEIGHT,
  DOT_LANE_HEIGHT,
  RECAST_LANE_HEIGHT,
  RULER_HEIGHT,
  LANE_LABEL_WIDTH,
  RESOURCE_DOT_SIZE,
  RESOURCE_DOT_GAP,
} from "./constants";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    flex: 1,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    position: "relative" as const,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  title: {
    margin: 0,
    fontSize: "18px",
    color: "#e0e0e0",
  },
  headerControls: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  toggleButton: {
    background: "none",
    border: "1px solid #555",
    borderRadius: "4px",
    color: "#aaa",
    fontSize: "12px",
    padding: "4px 10px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  potencyDisplay: {
    fontSize: "16px",
    color: "#aaa",
  },
  potencyValue: {
    fontSize: "22px",
    fontWeight: "bold",
    color: "#ffd700",
  },
  dropZone: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    borderRadius: "8px",
    transition: "background-color 0.2s",
    minHeight: "200px",
    overflow: "hidden",
  },
  dropZoneActive: {
    backgroundColor: "rgba(255, 215, 0, 0.05)",
  },
  placeholder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    minHeight: "160px",
    color: "#666",
    fontSize: "14px",
  },
  scrollContainer: {
    overflowX: "auto",
    overflowY: "auto",
    flex: 1,
    minHeight: 0,
    padding: "12px 0",
  },
  timelineContent: {
    position: "relative",
    minWidth: "100%",
    paddingLeft: 0,
  },
  insertIndicator: {
    position: "absolute",
    top: 0,
    bottom: RULER_HEIGHT,
    width: "2px",
    backgroundColor: "#ffd700",
    zIndex: 10,
    pointerEvents: "none",
    boxShadow: "0 0 6px rgba(255, 215, 0, 0.6)",
  },
  lane: {
    display: "flex",
    height: LANE_HEIGHT,
    position: "relative",
    marginBottom: "4px",
  },
  laneLabel: {
    width: LANE_LABEL_WIDTH,
    boxSizing: "border-box" as const,
    flexShrink: 0,
    fontSize: "12px",
    fontWeight: "bold",
    color: "#888",
    textTransform: "uppercase" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "8px",
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
  },
  laneContent: {
    position: "relative",
    flex: 1,
    borderBottom: "1px solid #2a2a4a",
  },
  skillBlock: {
    position: "absolute",
    top: "4px",
    height: LANE_HEIGHT - 8,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  recastBar: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "4px",
    backgroundColor: "rgba(100, 149, 237, 0.3)",
    borderRadius: "2px",
  },
  castTimeBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "4px",
    borderRadius: "2px",
    overflow: "hidden",
  },
  castTimeFill: {
    height: "100%",
    backgroundColor: "rgba(255, 183, 77, 0.6)",
    borderRadius: "2px",
  },
  animLockBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "4px",
    borderRadius: "2px",
    overflow: "hidden",
  },
  animLockFill: {
    height: "100%",
    backgroundColor: "rgba(255, 100, 100, 0.6)",
    borderRadius: "2px",
  },
  skillIcon: {
    width: ICON_SIZE,
    height: ICON_SIZE,
    borderRadius: "6px",
    overflow: "hidden",
    cursor: "grab",
    border: "1px solid rgba(255,255,255,0.2)",
    marginTop: "8px",
    flexShrink: 0,
    transition: "opacity 0.15s",
    position: "relative" as const,
  },
  skillIconError: {
    border: "2px solid #ef5350",
    boxShadow: "0 0 8px rgba(239, 83, 80, 0.6)",
  },
  skillIconComboWarning: {
    border: "2px solid #ff9800",
    boxShadow: "0 0 8px rgba(255, 152, 0, 0.6)",
  },
  skillIconSelected: {
    border: "2px solid #ffd700",
    boxShadow: "0 0 8px rgba(255, 215, 0, 0.6)",
  },
  skillIconDragging: {
    opacity: 0.3,
  },
  ogcdBlock: {
    position: "absolute",
    top: "8px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  ogcdIcon: {
    width: ICON_SIZE - 4,
    height: ICON_SIZE - 4,
    borderRadius: "50%",
    overflow: "hidden",
    cursor: "grab",
    border: "1px solid rgba(255,255,255,0.2)",
    flexShrink: 0,
    transition: "opacity 0.15s",
    position: "relative" as const,
  },
  ogcdIconError: {
    border: "2px solid #ef5350",
    boxShadow: "0 0 8px rgba(239, 83, 80, 0.6)",
  },
  ogcdIconSelected: {
    border: "2px solid #ffd700",
    boxShadow: "0 0 8px rgba(255, 215, 0, 0.6)",
  },
  ogcdIconDragging: {
    opacity: 0.3,
  },
  iconImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
  manualBadge: {
    position: "absolute" as const,
    left: "1px",
    bottom: "1px",
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    backgroundColor: "rgba(15, 15, 35, 0.85)",
    border: "1px solid #ffa726",
    color: "#ffa726",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none" as const,
  },
  skillPotency: {
    fontSize: "9px",
    color: "#888",
    marginTop: "2px",
    textAlign: "center" as const,
  },
  // リソースゲージレーン
  resourceLane: {
    display: "flex",
    height: RESOURCE_LANE_HEIGHT,
    position: "relative",
    marginBottom: "2px",
  },
  resourceLaneLabel: {
    width: LANE_LABEL_WIDTH,
    boxSizing: "border-box" as const,
    flexShrink: 0,
    fontSize: "11px",
    color: "#777",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "8px",
    whiteSpace: "pre-line" as const,
    textAlign: "right" as const,
    lineHeight: 1.2,
    overflow: "hidden",
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
  },
  resourceLaneContent: {
    position: "relative",
    flex: 1,
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  resourceMarker: {
    position: "absolute",
    top: "4px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "2px",
  },
  resourceDots: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
  },
  resourceDotGrid: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "center",
    gap: `${RESOURCE_DOT_GAP}px`,
  },
  resourceGauge: {
    position: "relative",
    width: 40,
    height: RESOURCE_DOT_SIZE,
    borderRadius: RESOURCE_DOT_SIZE / 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    overflow: "hidden",
  },
  resourceGaugeFill: {
    height: "100%",
    borderRadius: RESOURCE_DOT_SIZE / 2,
    transition: "width 0.2s",
  },
  resourceGaugeLabel: {
    position: "absolute" as const,
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "8px",
    fontWeight: "bold",
    color: "#fff",
    textShadow: "0 0 2px rgba(0,0,0,0.8)",
  },
  resourceDot: {
    width: RESOURCE_DOT_SIZE,
    height: RESOURCE_DOT_SIZE,
    borderRadius: "50%",
    // 背景色が濃いため、暗色リソース（BP 等）が空きスロットや背景と同化しないよう輪郭を付ける
    boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.25)",
    transition: "background-color 0.2s",
  },
  resourceErrorMark: {
    fontSize: "9px",
    fontWeight: "bold",
    color: "#ef5350",
    lineHeight: 1,
  },
  // バフレーン
  buffLane: {
    display: "flex",
    height: BUFF_LANE_HEIGHT,
    position: "relative",
    marginBottom: "2px",
  },
  buffLaneLabel: {
    width: LANE_LABEL_WIDTH,
    boxSizing: "border-box" as const,
    flexShrink: 0,
    fontSize: "11px",
    color: "#777",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "8px",
    whiteSpace: "pre-line" as const,
    textAlign: "right" as const,
    lineHeight: 1.2,
    overflow: "hidden",
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
  },
  buffLaneContent: {
    position: "relative",
    flex: 1,
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  buffBar: {
    position: "absolute",
    top: "4px",
    height: BUFF_LANE_HEIGHT - 8,
    borderRadius: "4px",
    border: "1px solid",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    paddingLeft: "2px",
    paddingRight: "6px",
    overflow: "hidden",
  },
  buffIcon: {
    width: "20px",
    height: "20px",
    borderRadius: "3px",
    flexShrink: 0,
    objectFit: "contain" as const,
  },
  buffDuration: {
    fontSize: "10px",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  ruler: {
    display: "flex",
    height: RULER_HEIGHT,
    position: "relative",
    borderTop: "1px solid #444",
    marginTop: "4px",
  },
  rulerLabel: {
    width: LANE_LABEL_WIDTH,
    flexShrink: 0,
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
  },
  rulerContent: {
    position: "relative",
    flex: 1,
  },
  rulerTick: {
    position: "absolute",
    top: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  rulerTickLine: {
    width: "1px",
    height: "100%",
    backgroundColor: "#555",
  },
  rulerTickLabel: {
    fontSize: "10px",
    color: "#777",
    marginTop: "2px",
    whiteSpace: "nowrap" as const,
  },
  // DoTレーン
  dotLane: {
    display: "flex",
    height: DOT_LANE_HEIGHT,
    position: "relative",
    marginBottom: "2px",
  },
  dotLaneLabel: {
    width: LANE_LABEL_WIDTH,
    boxSizing: "border-box" as const,
    flexShrink: 0,
    fontSize: "11px",
    color: "#777",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "8px",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
  },
  dotLaneContent: {
    position: "relative",
    flex: 1,
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  dotBar: {
    position: "absolute",
    top: "4px",
    height: DOT_LANE_HEIGHT - 12,
    borderRadius: "4px",
    border: "1px solid #a5d6a7",
    backgroundColor: "rgba(165, 214, 167, 0.15)",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    paddingLeft: "2px",
    paddingRight: "6px",
    overflow: "hidden",
  },
  dotIcon: {
    width: "18px",
    height: "18px",
    borderRadius: "3px",
    flexShrink: 0,
    objectFit: "contain" as const,
  },
  dotDuration: {
    fontSize: "10px",
    color: "#a5d6a7",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  dotTickMarker: {
    position: "absolute",
    top: "2px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    transform: "translateX(-50%)",
  },
  dotTickLine: {
    width: "1px",
    height: DOT_LANE_HEIGHT - 14,
    backgroundColor: "rgba(165, 214, 167, 0.5)",
  },
  dotTickPotency: {
    fontSize: "8px",
    color: "#a5d6a7",
    whiteSpace: "nowrap" as const,
  },
  // リキャストレーン
  recastLane: {
    display: "flex",
    height: RECAST_LANE_HEIGHT,
    position: "relative",
    marginBottom: "2px",
  },
  recastLaneLabel: {
    width: LANE_LABEL_WIDTH,
    boxSizing: "border-box" as const,
    flexShrink: 0,
    fontSize: "11px",
    color: "#777",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: "8px",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    position: "sticky" as const,
    left: 0,
    zIndex: 6,
    backgroundColor: "#0f0f23",
    gap: "3px",
  },
  recastLabelIcon: {
    width: "16px",
    height: "16px",
    borderRadius: "3px",
    flexShrink: 0,
    objectFit: "contain" as const,
  },
  recastLaneContent: {
    position: "relative",
    flex: 1,
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  cooldownBar: {
    position: "absolute",
    top: "3px",
    height: RECAST_LANE_HEIGHT - 6,
    borderRadius: "4px",
    border: "1px solid #90caf9",
    backgroundColor: "rgba(144, 202, 249, 0.12)",
    display: "flex",
    alignItems: "center",
    gap: "3px",
    paddingLeft: "2px",
    paddingRight: "6px",
    overflow: "hidden",
  },
  recastIcon: {
    width: "16px",
    height: "16px",
    borderRadius: "3px",
    flexShrink: 0,
    objectFit: "contain" as const,
  },
  recastDuration: {
    fontSize: "10px",
    color: "#90caf9",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  hint: {
    marginTop: "8px",
    fontSize: "12px",
    color: "#555",
    textAlign: "center" as const,
  },
  deleteDropZone: {
    position: "absolute" as const,
    bottom: 32,
    left: 32,
    right: 32,
    padding: "28px 44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    backgroundColor: "rgba(211, 47, 47, 0.85)",
    color: "#fff",
    border: "2px dashed rgba(255, 255, 255, 0.5)",
    borderRadius: 12,
    boxShadow: "0 6px 24px rgba(0, 0, 0, 0.5)",
    fontSize: 18,
    fontWeight: "bold" as const,
    zIndex: 1000,
    userSelect: "none" as const,
    transition: "transform 0.15s, background-color 0.15s, border-color 0.15s",
  },
  deleteDropZoneActive: {
    backgroundColor: "rgba(211, 47, 47, 1)",
    borderColor: "rgba(255, 255, 255, 0.95)",
    transform: "scale(1.02)",
  },
  deleteDropZoneIcon: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 28,
    lineHeight: 1,
  },
  deleteDropZoneLabel: {
    whiteSpace: "nowrap" as const,
  },
  // ボス離脱エディタ
  untargetableEditor: {
    backgroundColor: "rgba(255, 80, 80, 0.05)",
    border: "1px solid rgba(255, 80, 80, 0.2)",
    borderRadius: "6px",
    padding: "8px 12px",
    marginBottom: "8px",
  },
  untargetableHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "6px",
  },
  untargetableTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#ef5350",
  },
  untargetableAddButton: {
    background: "none",
    border: "1px solid rgba(255, 80, 80, 0.4)",
    borderRadius: "4px",
    color: "#ef5350",
    fontSize: "12px",
    padding: "2px 10px",
    cursor: "pointer",
  },
  untargetableEmpty: {
    fontSize: "12px",
    color: "#777",
  },
  untargetableRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "4px",
  },
  untargetableLabel: {
    fontSize: "12px",
    color: "#aaa",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  untargetableInput: {
    width: "60px",
    backgroundColor: "#1a1a3e",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    padding: "2px 6px",
    fontSize: "12px",
    textAlign: "right" as const,
  },
  untargetableDeleteButton: {
    background: "none",
    border: "1px solid rgba(255, 80, 80, 0.3)",
    borderRadius: "4px",
    color: "#ef5350",
    fontSize: "12px",
    padding: "2px 8px",
    cursor: "pointer",
    lineHeight: 1,
  },
  // 複数体ウィンドウエディタ
  multiTargetEditor: {
    backgroundColor: "rgba(180, 100, 220, 0.05)",
    border: "1px solid rgba(180, 100, 220, 0.2)",
    borderRadius: "6px",
    padding: "8px 12px",
    marginBottom: "8px",
  },
  multiTargetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "6px",
  },
  multiTargetTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#b864dc",
  },
  multiTargetAddButton: {
    background: "none",
    border: "1px solid rgba(180, 100, 220, 0.4)",
    borderRadius: "4px",
    color: "#b864dc",
    fontSize: "12px",
    padding: "2px 10px",
    cursor: "pointer",
  },
  multiTargetEmpty: {
    fontSize: "12px",
    color: "#777",
  },
  multiTargetRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "4px",
  },
  multiTargetLabel: {
    fontSize: "12px",
    color: "#aaa",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  multiTargetInput: {
    width: "60px",
    backgroundColor: "#1a1a3e",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    padding: "2px 6px",
    fontSize: "12px",
    textAlign: "right" as const,
  },
  multiTargetDeleteButton: {
    background: "none",
    border: "1px solid rgba(180, 100, 220, 0.3)",
    borderRadius: "4px",
    color: "#b864dc",
    fontSize: "12px",
    padding: "2px 8px",
    cursor: "pointer",
    lineHeight: 1,
  },
  // PPS表示
  ppsDisplay: {
    fontSize: "14px",
    color: "#ffb74d",
    marginLeft: "8px",
  },
  ppsValue: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#ffb74d",
  },
  // PPS範囲選択エディタ
  ppsRangeEditor: {
    backgroundColor: "rgba(255, 183, 77, 0.05)",
    border: "1px solid rgba(255, 183, 77, 0.2)",
    borderRadius: "6px",
    padding: "8px 12px",
    marginBottom: "8px",
  },
  ppsRangeHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "6px",
  },
  ppsRangeTitle: {
    fontSize: "13px",
    fontWeight: "bold",
    color: "#ffb74d",
  },
  ppsRangeRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "4px",
  },
  ppsRangeLabel: {
    fontSize: "12px",
    color: "#aaa",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  ppsRangeInput: {
    width: "60px",
    backgroundColor: "#1a1a3e",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    padding: "2px 6px",
    fontSize: "12px",
    textAlign: "right" as const,
  },
  ppsRangeResetButton: {
    background: "none",
    border: "1px solid rgba(255, 183, 77, 0.4)",
    borderRadius: "4px",
    color: "#ffb74d",
    fontSize: "12px",
    padding: "2px 10px",
    cursor: "pointer",
  },
  ppsRangeResult: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#e0e0e0",
    marginTop: "4px",
  },
  ppsRangeDetail: {
    fontSize: "12px",
    color: "#888",
  },
};
